# Generated by Django 5.0.6 on 2024-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='naciomiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autores',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autores',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
