# Generated by Django 5.0.6 on 2024-05-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_autores_naciomiento_autores_nacionalidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autores',
        ),
    ]
