# Generated by Django 5.0.4 on 2024-05-30 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='producto',
            new_name='libro',
        ),
    ]
