# Generated by Django 5.0.4 on 2024-05-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_remove_libro_autor_libro_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroPorAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libros', models.ManyToManyField(to='libros.libro')),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.autores')),
            ],
        ),
    ]
