# Generated by Django 5.0.4 on 2024-05-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libroporautor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autores',
            old_name='nombre',
            new_name='nombre_autor',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='nombre',
            new_name='nombre_libro',
        ),
    ]
