# Generated by Django 5.0.4 on 2024-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_rename_naciomiento_autores_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='numero_paginas',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
