# Generated by Django 5.0.4 on 2024-05-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_libro_genero_libro_numero_paginas_libro_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='unidades',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
