# Generated by Django 5.0.4 on 2024-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_libro_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='año',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libroporautor',
            name='libros',
            field=models.ManyToManyField(blank=True, null=True, to='libros.libro'),
        ),
    ]
