# Generated by Django 5.0.4 on 2024-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0010_libro_año_alter_libroporautor_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroporautor',
            name='libros',
            field=models.ManyToManyField(to='libros.libro'),
        ),
    ]
