# Generated by Django 5.0.4 on 2024-05-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0012_alter_libro_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='libros',
            field=models.ManyToManyField(to='libros.libro'),
        ),
        migrations.AlterField(
            model_name='autores',
            name='nombre_autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='LibroPorAutor',
        ),
    ]
