# Generated by Django 5.0.4 on 2024-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0013_autores_libros_alter_autores_nombre_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='libros',
            field=models.ManyToManyField(blank=True, null=True, to='libros.libro'),
        ),
    ]
