# Generated by Django 5.0.4 on 2024-05-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0014_alter_autores_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='libros',
            field=models.ManyToManyField(to='libros.libro'),
        ),
    ]
